# Generated by Django 3.1.5 on 2021-01-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210111_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='start_year',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
