# Generated by Django 3.1.5 on 2021-01-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210113_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.university'),
            preserve_default=False,
        ),
    ]
